package org.lunifera.example.vaadin.ecview.samples;

import java.util.Date;

import org.eclipse.emf.ecp.ecview.common.context.ContextException;
import org.eclipse.emf.ecp.ecview.extension.model.extension.util.SimpleExtensionModelFactory;
import org.lunifera.example.vaadin.ecview.Activator;
import org.lunifera.example.vaadin.ecview.SampleEntity;
import org.lunifera.runtime.web.ecview.services.vaadin.IECViewUIRenderService;

import com.vaadin.shared.ui.label.ContentMode;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;

/**
 * Demonstrates databinding between fields based on ECView and EMF bindings.
 */
@SuppressWarnings("serial")
public class ECViewEntityGenerator extends CssLayout {

	private SimpleExtensionModelFactory factory = new SimpleExtensionModelFactory();

	private VerticalLayout layout;

	public ECViewEntityGenerator() throws ContextException {
		setSizeFull();
		init();
	}

	public void init() throws ContextException {

		// Vaadin basis ...
		layout = new VerticalLayout();
		addComponent(layout);

		layout.addComponent(new Label(
				"<h3>View automatically generated by Sample.entitymodel</h3>",
				ContentMode.HTML));
		SampleEntity entity = createSampleEntity();

		// render the UI
		IECViewUIRenderService renderingService = Activator.getPlugin()
				.getRenderService();
		renderingService.renderUIForEntity(entity, layout, null, null);

	}

	/**
	 * Creates the sample entity.
	 * 
	 * @return
	 */
	public SampleEntity createSampleEntity() {
		SampleEntity entity = new SampleEntity();
		entity.setNumber("XXA-11234");
		entity.setDescription("Sample Entity with number XXA-11234");
		entity.setBooleanAttribute(true);
		entity.setDateAttribute(new Date());
		entity.setTimeAttribute(new Date());
		entity.setDecimalAttribute(22.587d);
		entity.setNumericAttribute(11223344);
		return entity;
	}

}
