package org.lunifera.example.vaadin.ecview.samples;

import java.util.Date;

import org.eclipse.emf.ecp.ecview.common.context.ContextException;
import org.eclipse.emf.ecp.ecview.extension.model.extension.util.SimpleExtensionModelFactory;
import org.lunifera.example.vaadin.ecview.Activator;
import org.lunifera.example.vaadin.ecview.dtos.SampleDto;
import org.lunifera.runtime.web.ecview.services.vaadin.IECViewUIRenderService;

import com.vaadin.shared.ui.label.ContentMode;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;

/**
 * Demonstrates databinding between fields based on ECView and EMF bindings.
 */
@SuppressWarnings("serial")
public class ECViewDtoGenerator extends CssLayout {

	private SimpleExtensionModelFactory factory = new SimpleExtensionModelFactory();

	private VerticalLayout layout;

	public ECViewDtoGenerator() throws ContextException {
		setSizeFull();
		init();
	}

	public void init() throws ContextException {

		// Vaadin basis ...
		layout = new VerticalLayout();
		addComponent(layout);

		layout.addComponent(new Label(
				"<h3>View automatically generated by Sample.dtos</h3>",
				ContentMode.HTML));
		SampleDto dto = createSampleDto();

		// render the UI
		IECViewUIRenderService renderingService = Activator.getPlugin()
				.getRenderService();
		renderingService.renderUIForDTO(dto, layout, null, null);

		// add a second view to see the power of databinding
		layout.addComponent(new Label(
				"<h3>Render the same view twice to see proper databinding</h3>",
				ContentMode.HTML));
		renderingService.renderUIForDTO(dto, layout, null, null);
	}

	/**
	 * Creates the sample entity.
	 * 
	 * @return
	 */
	public SampleDto createSampleDto() {
		SampleDto dto = new SampleDto();
		dto.setNumber("XXA-11234");
		dto.setDescription("Sample Entity with number XXA-11234");
		dto.setBooleanAttribute(true);
		dto.setDateAttribute(new Date());
		dto.setTimeAttribute(new Date());
		dto.setDecimalAttribute(22.587d);
		dto.setNumericAttribute(11223344);
		return dto;
	}

}
